"""Sensor fusion, accident detection and the emergency response state machine."""

from running.detection.fusion import (
    DEFAULT_CONFIDENCE_THRESHOLD,
    MIN_CONTRIBUTING_SIGNALS,
    assess,
    fuse,
)
from running.detection.impact import detect_impact
from running.detection.models import (
    ActivitySample,
    ImpactEvent,
    MotionSample,
    SignalScore,
    StressAssessment,
)
from running.detection.response import (
    AlarmReason,
    Dismissed,
    DismissPrompt,
    DistressConfirmed,
    RaiseAlarm,
    RecordingChoice,
    ResponseConfig,
    ResponseMachine,
    ResponseState,
    ShowConfirmationPrompt,
    ShowRecordingPrompt,
    StartRecording,
    StopRecording,
    ThresholdCrossed,
    Tick,
    Trigger,
)
from running.detection.signals import (
    ActivityAdjustedDetector,
    DetectionContext,
    PhasicEDADetector,
    SignalDetector,
    activity_series,
    detectors,
    register_detector,
)

__all__ = [
    "DEFAULT_CONFIDENCE_THRESHOLD",
    "MIN_CONTRIBUTING_SIGNALS",
    "ActivityAdjustedDetector",
    "ActivitySample",
    "AlarmReason",
    "DetectionContext",
    "DismissPrompt",
    "Dismissed",
    "DistressConfirmed",
    "ImpactEvent",
    "MotionSample",
    "PhasicEDADetector",
    "RaiseAlarm",
    "RecordingChoice",
    "ResponseConfig",
    "ResponseMachine",
    "ResponseState",
    "ShowConfirmationPrompt",
    "ShowRecordingPrompt",
    "SignalDetector",
    "SignalScore",
    "StartRecording",
    "StopRecording",
    "StressAssessment",
    "ThresholdCrossed",
    "Tick",
    "Trigger",
    "activity_series",
    "assess",
    "detect_impact",
    "detectors",
    "fuse",
    "register_detector",
]
